### ISSUE TITLE
What if I have lots of constraints?

### ISSUE THREAD

**Issue by fantasycz** [coldfix/Citip#8]
I want to proof a inequality. However, I have many constraints, say 20 and 12 variables. Is there any easy way to run? Thank you.

**Comment by coldfix** [comment]
Hi, 12 variables is high but should still be possible: 12 random variables means there are 67596 elemental inequalities with 4095 entries each. 20 additional constraints shouldn't be any problem whatsoever.

The [Usage](https://github.com/coldfix/Citip#usage) section in the README shows how to do it.
